# Generated by Django 2.2.3 on 2019-08-05 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('location', models.CharField(default='', max_length=50, verbose_name='Your Location')),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('picture', models.ImageField(null=True, upload_to='users_pic')),
                ('money', models.PositiveIntegerField(default=0)),
                ('is_company', models.BooleanField(default=True, help_text="Designates whether You're company or not", verbose_name='Company')),
                ('is_valid_profile', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(default='', max_length=200)),
                ('length', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('giver_acceptance', models.BooleanField(default=False)),
                ('receiver_acceptance', models.BooleanField(default=False, help_text="Don't check this until your receive your money ")),
                ('final_amount', models.PositiveIntegerField(default=0)),
                ('loaned_at', models.DateField(blank=True, null=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_giver', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(default=0)),
                ('expected_date', models.DateField()),
                ('final_date', models.DateField(blank=True, null=True)),
                ('received', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='app.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='Citizien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(19999999)])),
                ('last_name', models.CharField(editable=False, max_length=25)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
