# Generated by Django 2.2.3 on 2019-07-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lonaed_at', models.DateTimeField(editable=False)),
                ('length', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_giver', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
