# Generated by Django 2.2.3 on 2019-07-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='lonaed_at',
            new_name='loaned_at',
        ),
    ]
