# Generated by Django 2.2.3 on 2019-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190718_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='users_pic'),
        ),
    ]
