# Generated by Django 2.2.3 on 2019-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190718_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
