# Generated by Django 2.2.3 on 2019-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190721_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loaned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
