# Generated by Django 2.2.3 on 2019-07-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190721_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
