# Generated by Django 2.2.3 on 2019-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190722_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
