# Generated by Django 2.2.3 on 2019-07-24 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(19999999)]),
        ),
    ]
