# Generated by Django 2.2.3 on 2019-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190724_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
