# Generated by Django 2.2.3 on 2019-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_loan_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='accepted',
            new_name='giver_acceptance',
        ),
        migrations.AddField(
            model_name='loan',
            name='final_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='next_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='receiver_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
