# Generated by Django 2.2.3 on 2019-07-25 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190724_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='next_payment',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='receiver_acceptance',
            field=models.BooleanField(default=False, help_text="Don't check this until your receive your money "),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(19999999)]),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(default=0)),
                ('expected_date', models.DateField()),
                ('final_date', models.DateField(blank=True, null=True)),
                ('received', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='app.Loan')),
            ],
        ),
    ]
