# Generated by Django 2.2.3 on 2019-07-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190725_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loaned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
