# Generated by Django 2.2.3 on 2019-07-29 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190725_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_compay',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=50, verbose_name='Your Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(19999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Citizien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(19999999)])),
                ('last_name', models.CharField(max_length=25)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
