# Generated by Django 2.2.3 on 2019-07-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190729_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_compay',
            new_name='is_company',
        ),
    ]
