# Generated by Django 2.2.3 on 2019-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190729_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valid_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=True, help_text="Designates whether You're company or not", verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
