# Generated by Django 2.2.3 on 2019-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190729_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizien',
            name='last_name',
            field=models.CharField(editable=False, max_length=25),
        ),
    ]
